# Generated by Django 5.1.4 on 2025-01-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100)),
                ('p_phone', models.BigIntegerField()),
                ('p_email', models.EmailField(max_length=254)),
                ('dep_name', models.CharField(max_length=100)),
                ('doc_name', models.CharField(max_length=100)),
                ('booking_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=100)),
                ('dep_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_spec', models.CharField(max_length=100)),
                ('doc_name', models.CharField(max_length=100)),
                ('dep_name', models.CharField(max_length=100)),
                ('doc_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
