# Generated by Django 5.1.4 on 2025-01-05 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_doctors_dep_name_alter_doctors_doc_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='dep_name',
        ),
        migrations.AddField(
            model_name='booking',
            name='booked_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='doc_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.doctors'),
        ),
    ]
